### ISSUE TITLE
RFC: Provider configuration file spec

### ISSUE THREAD

**Issue by markafarrell** [openpubkey/opkssh#115]
Just wanted to start an issue so we can discuss what the configuration file spec should look like for providers.

Currently we use space delimited config in `/etc/opk/providers`

We could replace this with a yaml based configuration.

e.g.
`/etc/opk/providers.yml`
```yaml
---
providers:
  google:
    issuer: https://accounts.google.com
    client_id: 206584157355-7cbe4s640tvm7naoludob4ut1emii7sf.apps.googleusercontent.com 
    expiration_policy: 24h
  azure:
    issuer: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
    client_id: 096ce0a3-5e72-4da8-9c86-12924b294a01 
    expiration_policy: 24h
  gitlab:
    issuer: https://gitlab.com
    client_id: 8d8b7024572c7fd501f64374dec6bba37096783dfcd792b3988104be08cb6923
    expiration_policy: 24h
```

To extend this we could also support adding or modifying providers by reading from `/etc/opk/providers.d/*.yml`

e.g.
`/etc/opk/providers.d/my-op.yml`
```yaml
---
providers:
  my-op:
    issuer: https://my.op
    client_id: my-client-id 
    expiration_policy: 24h
```
This would result in a combined provider configuration of:

```yaml
---
providers:
  google:
    issuer: https://accounts.google.com
    client_id: 206584157355-7cbe4s640tvm7naoludob4ut1emii7sf.apps.googleusercontent.com 
    expiration_policy: 24h
  azure:
    issuer: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
    client_id: 096ce0a3-5e72-4da8-9c86-12924b294a01 
    expiration_policy: 24h
  gitlab:
    issuer: https://gitlab.com
    client_id: 8d8b7024572c7fd501f64374dec6bba37096783dfcd792b3988104be08cb6923
    expiration_policy: 24h
  my-op:
    issuer: https://my.op
    client_id: my-client-id 
    expiration_policy: 24h
```

We essential merge the yaml dictionaries.

To modify providers we could do the following:

`/etc/opk/providers.d/google.yml`
```yaml
---
providers:
  google:
    expiration_policy: 1h
```
This would result in a combined provider configuration of:

```yaml
providers:
  google:
    issuer: https://accounts.google.com
    client_id: 206584157355-7cbe4s640tvm7naoludob4ut1emii7sf.apps.googleusercontent.com 
    expiration_policy: 1h
  azure:
    issuer: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
    client_id: 096ce0a3-5e72-4da8-9c86-12924b294a01 
    expiration_policy: 24h
  gitlab:
    issuer: https://gitlab.com
    client_id: 8d8b7024572c7fd501f64374dec6bba37096783dfcd792b3988104be08cb6923
    expiration_policy: 24h
  my-op:
    issuer: https://my.op
    client_id: my-client-id 
    expiration_policy: 24h
```
Again this is acheived by merging the yaml dictionaries.

Files in `/etc/opk/providers.d/` should be loaded/processed in alphabetical order to allow the user to control the precedence of files (i.e. last loaded/processed file has highest precedence)

**Comment by markafarrell** [comment]
We could also disable providers using this approach too

`/etc/opk/providers.d/azure.yml`
```yaml
---
providers:
  azure: {}
```
