### ISSUE TITLE
BUG: Authelia implementation ignores the `groups` scope

### ISSUE THREAD

**Issue by davidedpg10** [openpubkey/opkssh#144]
I don't entirely know if this is a bug on Authelia's OIDC implementation or OPKSSH. The instructions found here: https://www.authelia.com/integration/openid-connect/opkssh/ do not include a `groups` scope for setting up an OPKSSH OIDC provider, however Authelia does support it (as shown in the [OIDC documentation for mealie](https://www.authelia.com/integration/openid-connect/mealie/))
I have also setup a Mealie instance and added/removed the logged in user from the administrator group for Mealie to ensure group is being passed along, and I saw the behavior change, in addition to the login screen difference (as seen in the included screenshots):

![Image](https://github.com/user-attachments/assets/e5062eff-ef7e-41cd-b1fa-1efa200b0735)

![Image](https://github.com/user-attachments/assets/3ec5d666-b409-4920-9b05-dc87a08e0246)

The `scopes` section for both OIDC clients looks the same on my configuration:
```
    clients:
      # Issuer:
      - client_id: mealie
        client_name: Mealie
        client_secret: <redacted>
        redirect_uris:
          - https://recipes.example.com/login
        scopes:
          - openid
          - profile
          - email
          - groups
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        userinfo_signed_response_alg: 'none'
        authorization_policy: mealie_policy
      - client_id: opkssh
        client_name: opkssh
        public: true
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'http://localhost:3000/login-callback'
          - 'http://localhost:10001/login-callback'
          - 'http://localhost:11110/login-callback'
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signed_response_alg: 'none'
```

Is this something on the OKPSSH side or on the Authelia side?
