### ISSUE TITLE
Issues with connecting using `authelia`

### ISSUE THREAD

**Issue by vigneshmanick** [openpubkey/opkssh#225]
Hello Team, 

I am currently testing `opkssh` with `authelia` and have run into a couple of issues. I followed the steps at https://www.authelia.com/integration/openid-connect/opkssh/ and i face the following issues

- If the configuration option `token_endpoint_auth_method: 'client_secret_basic'` is used, Authelia errors out saying that the option should be set to `none` 
- After setting the above option to `none` authelia starts successfully. I tested the login from Windows client to Linux server.  (`my-domain.com` is a placeholder for the actual domain used)
  -  `.\opkssh-windows-amd64.exe login --provider=https://auth.my-domain.com/,opkssh` , here i get the error
      
```
      Error executing login command: error logging in: error requesting OIDC tokens from OpenID Provider: error creating provider: issuer does not match
Error: error logging in: error requesting OIDC tokens from OpenID Provider: error creating provider: issuer does not match
```
  - If i remove the `/` at the end of the command and run   `.\opkssh-windows-amd64.exe login --provider=https://auth.my-domain.com,opkssh` , i get to the authelia login portal but after login and clicking on accept the browser errors out with the following 

![Image](https://github.com/user-attachments/assets/730a0ac2-0607-457c-8b84-beb636e079ab)

What am i doing wrong ?

Thanks!

**Comment by vigneshmanick** [comment]
getting closer,  the url that is returned in the browser is prefixed with `https` , see image 

![Image](https://github.com/user-attachments/assets/0fcc379c-8666-4f86-8b0e-1e78c0b3213a)

if i change this url directly in the browser to `http`  then i get the message `You may now close this window, Writing opk ssh public key to C:\Users\vm\.ssh\id_ecdsa.pub `

Now the question is, how to change the redirect uri automatically to `http`, i checkd the `authelia` `configuration.yml` and it's set as `http:localhost:3000` there, so this should be either the nginx proxy/authelia itself that is redirecting to `https`

**Comment by EthanHeilman** [comment]
Looking into this

**Comment by EthanHeilman** [comment]
Just to clarify your configuration.yml looks like this?

```yaml
redirect_uris:
  - 'http://localhost:3000/login-callback'
  - 'http://localhost:10001/login-callback'
  - 'http://localhost:11110/login-callback'
```

It does appear that some recent changes  to the authelia opkssh guide that may have broken things. For instance https://github.com/authelia/authelia/pull/9342 introduced the first bug you hit by adding `token_endpoint_auth_method: 'client_secret_basic'` 

Can you try to use original version of the config as it was verified to work?

```yaml {title="configuration.yml"}
identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:
      - client_id: 'opkssh'
        client_name: 'opkssh'
        public: true
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'http://localhost:3000/login-callback'
          - 'http://localhost:10001/login-callback'
          - 'http://localhost:11110/login-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```
https://github.com/authelia/authelia/blob/7c86c71bde79a8f1910eb77a5dba450d418710ca/docs/content/integration/openid-connect/opkssh/index.md

Can you confirm which version of authelia you are using? I want to see if they introduced any changes that may be breaking the redirect URI

**Comment by vm-cfdschuck** [comment]
> ust to clarify your configuration.yml looks like this?
Yes


The original version is what i have now where i got the issue of redirection to the `https` page instead of the `http` as set in the configuration.yml. 


The authelia version i am using is 4.39.4

The current configuration for `opkssh` what i have is 

```yml
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    claims_policies:
      ## Creates the 'default' claims policy.
      opkssh:
        id_token: ['email']
  clients:      
     - client_id: 'longclientid'
        client_name: 'opkssh'
        claims_policy: 'opkssh'
        public: true
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'http://localhost:3000/login-callback'
          - 'http://localhost:10001/login-callback'
          - 'http://localhost:11110/login-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```
