### ISSUE TITLE
Add a generic OIDC provider for other IDPs

### ISSUE THREAD

**Issue by s-anvar** [openpubkey/opkssh#38]
Would be great to see a generic OIDC provider to support other IDPs.

**Comment by LeeTeng2001** [comment]
specifically for self hosted infrastructure like authentik and authelia

**Comment by EthanHeilman** [comment]
@LeeTeng2001 This merged PR adds generic OPs

https://github.com/openpubkey/opkssh/pull/58

Can you test this and report back if it works for what you need?

What do you think about this generic OP configuration file?

https://github.com/openpubkey/opkssh/pull/60

**Comment by EthanHeilman** [comment]
@zukka77 Did you have to do anything special to get it work with keycloak?

**Comment by hendrik1120** [comment]
@EthanHeilman I tested it with authelia and got it working eventually.

I don't think the instructions in the README are correct.

I had to use:
```
opkssh login -provider auth.example.com,opkssh,
```
The last comma is very important, because otherwise a client secret will still be included.
Authelia validates that public clients are using no token auth method.

On the server I used:
`/etc/opk/providers`
```
https://auth.example.com opkssh 24h
```
which is again differing from the documentation. Am I missing something?

Since opkssh is not able to query the userinfo endpoint for information not included in the ID Token and is also not using the claims parameter, the claims have to be explicitly included in the ID Token. https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter

This is my client config for authelia 4.39
```yaml
identity_providers:
  oidc:
    claims_policies:
      default:
        id_token: ['groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
    clients:
      - client_id: 'opkssh'
        client_name: 'opkssh'
        public: true
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'one_factor'
        claims_policy: 'default'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        redirect_uris:
          - 'http://localhost:3000/login-callback'
```
